(()=>{
  'use strict';
  const MIN=3,SEATS=['블루존','3루 내야 지정석','1루 내야 지정석','중앙 테이블석','익사이팅존','SKY 지정석','외야 지정석','잔디석'];
  const $=(s,r=document)=>r.querySelector(s),safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const st=()=>typeof state!=='undefined'?state:null,ms=()=>st()?.members||[],gs=()=>st()?.games||[],ats=()=>st()?.gameMembers||[],done=g=>g&&g.status==='FINISHED'&&['W','L','D'].includes(g.result);
  function streak(a,x){let n=0,b=0;a.forEach(g=>{n=g.result===x?n+1:0;b=Math.max(b,n)});return b}
  function records(){return ms().map(member=>{const watched=ats().filter(e=>e.member_id===member.id&&e.attended).map(e=>gs().find(g=>g.id===e.game_id)).filter(done).sort((a,b)=>a.game_date.localeCompare(b.game_date)),wins=watched.filter(g=>g.result==='W').length,losses=watched.filter(g=>g.result==='L').length,draws=watched.filter(g=>g.result==='D').length,home=watched.filter(g=>g.home_away==='HOME'),away=watched.filter(g=>g.home_away==='AWAY'),ops={};watched.forEach(g=>ops[g.opponent]=(ops[g.opponent]||0)+1);return{member,watched,wins,losses,draws,rate:wins+losses?wins/(wins+losses):0,home,away,homeWins:home.filter(g=>g.result==='W').length,homeLosses:home.filter(g=>g.result==='L').length,awayWins:away.filter(g=>g.result==='W').length,awayLosses:away.filter(g=>g.result==='L').length,topOpponent:Object.entries(ops).sort((a,b)=>b[1]-a[1])[0],avgRuns:watched.length?(watched.reduce((n,g)=>n+(+g.samsung_score||0),0)/watched.length).toFixed(1):'-',stadiums:new Set(watched.map(g=>g.stadium).filter(Boolean)).size,winStreak:streak(watched,'W'),lossStreak:streak(watched,'L'),highScore:watched.some(g=>(+g.samsung_score||0)>=10),shutoutWin:watched.some(g=>g.result==='W'&&+g.opponent_score===0),shutoutLoss:watched.some(g=>g.result==='L'&&+g.samsung_score===0)}})}
  const defs=()=>[
    ['첫 직관','🎟️','첫 직관 완료',r=>r.watched.length>=1,'good'],['입문 완료','🌱','직관 3경기',r=>r.watched.length>=3,'good'],['시즌 5경기','🖐️','직관 5경기',r=>r.watched.length>=5,'good'],['두 자릿수 직관','🔟','직관 10경기',r=>r.watched.length>=10,'good'],['라팍 지박령','🏟️','홈 직관 15경기',r=>r.home.length>=15,'good'],['찐 야구인','🦁','직관 20경기',r=>r.watched.length>=20,'good'],['개근왕','👑','직관 30경기',r=>r.watched.length>=30,'good'],['첫 승리','💙','직관 첫 승리',r=>r.wins>=1,'good'],['승리 수집가','🏆','직관 5승',r=>r.wins>=5,'good'],['승리의 파랑새','🐦','직관 10승',r=>r.wins>=10,'good'],['왕조의 증인','👑','직관 20승',r=>r.wins>=20,'good'],['연승 시동','🔥','직관 3연승',r=>r.winStreak>=3,'good'],['불패의 주말','⚡','직관 5연승',r=>r.winStreak>=5,'good'],['승률 7할','📈','5경기 이상, 승률 70%',r=>r.watched.length>=5&&r.rate>=.7,'good'],['승률 8할','💎','10경기 이상, 승률 80%',r=>r.watched.length>=10&&r.rate>=.8,'good'],['원정대','🚌','첫 원정 직관',r=>r.away.length>=1,'neutral'],['전국구','🗺️','3개 구장 방문',r=>r.stadiums>=3,'neutral'],['전국 투어','🚄','5개 구장 방문',r=>r.stadiums>=5,'neutral'],['홈 보안관','🤠','홈 직관 5승',r=>r.homeWins>=5,'good'],['원정 승부사','⚔️','원정 직관 3승',r=>r.awayWins>=3,'good'],['난타전 목격자','💥','삼성 10득점 이상 경기 직관',r=>r.highScore,'neutral'],['철벽 목격자','🧱','삼성 무실점 승리 직관',r=>r.shutoutWin,'good'],['무승부도 야구다','🤝','무승부 경기 직관',r=>r.draws>=1,'neutral'],['첫 패배','🥲','직관 첫 패배',r=>r.losses>=1,'bad'],['패배 적응기','☔','직관 3패',r=>r.losses>=3,'bad'],['멘탈 단련','🧘','직관 5패',r=>r.losses>=5,'bad'],['보살 팬','🙏','직관 10패',r=>r.losses>=10,'bad'],['연패의 그림자','🌧️','직관 3연패',r=>r.lossStreak>=3,'bad'],['불운의 아이콘','🫥','직관 5연패',r=>r.lossStreak>=5,'bad'],['영봉패 목격자','🥚','삼성 무득점 패배 직관',r=>r.shutoutLoss,'bad'],['승률 3할대','📉','5경기 이상, 승률 40% 미만',r=>r.watched.length>=5&&r.rate<.4,'bad'],['패배요정 후보','💀','5경기 이상, 패가 승보다 많음',r=>r.watched.length>=5&&r.losses>r.wins,'bad'],['한 팀만 판다','🎯','같은 상대 경기 5회 직관',r=>r.topOpponent&&r.topOpponent[1]>=5,'neutral'],['다양성 추구','🌈','상대 5팀 이상 직관',r=>new Set(r.watched.map(g=>g.opponent)).size>=5,'neutral'],['홈 전용 팬','🛋️','직관 5경기 이상 모두 홈',r=>r.watched.length>=5&&r.away.length===0,'neutral'],['원정 체질','🎒','원정 직관이 홈보다 많음',r=>r.watched.length>=3&&r.away.length>r.home.length,'neutral']];
  const badges=r=>defs().map(([n,i,d,toneTest,tone])=>[n,i,!!toneTest(r),d,tone]);
  function pair(a,b){const ids=new Set(ats().filter(e=>e.member_id===a&&e.attended).map(e=>e.game_id)),shared=ats().filter(e=>e.member_id===b&&e.attended&&ids.has(e.game_id)).map(e=>gs().find(g=>g.id===e.game_id)).filter(done),wins=shared.filter(g=>g.result==='W').length,losses=shared.filter(g=>g.result==='L').length,draws=shared.filter(g=>g.result==='D').length;return{shared,wins,losses,draws,score:shared.length?Math.round((wins+.5*draws)/shared.length*100):0}}
  function ensure(){const rec=$('#records');if(!rec)return;$('#fanGameDay')?.remove();if(!$('#fanExperience'))rec.insertAdjacentHTML('afterbegin','<div id="fanExperience"></div>');if(!$('#fanModal'))document.body.insertAdjacentHTML('beforeend','<div id="fanModal" class="fan-modal"><div class="fan-modal-panel"><div class="fan-modal-head"><h3 id="fanModalTitle"></h3><button data-fan-close>닫기</button></div><div id="fanModalBody"></div></div></div>')}
  const options=(skip=0)=>ms().map((m,i)=>`<option value="${m.id}" ${i===skip?'selected':''}>${safe(m.name)}</option>`).join(''),seatData=()=>{try{return JSON.parse(localStorage.getItem('eoheung_seat_catalog')||'[]')}catch{return[]}};
  function linkNames(){const map=new Map(ms().map(m=>[m.name,m.id]));document.querySelectorAll('#recordAttendRank li b,#recordWinRank li b,#recordRateRank li b,#recordRows tr td:first-child b').forEach(el=>{if(el.closest('[data-fan-member]'))return;const id=map.get(el.textContent.trim());if(id)el.outerHTML=`<button class="fan-member-button" data-fan-member="${id}">${safe(el.textContent.trim())}</button>`})}
  function render(){ensure();const root=$('#fanExperience');if(!root)return;const rs=records(),eligible=rs.filter(r=>r.watched.length>=MIN),best=[...eligible].sort((a,b)=>b.rate-a.rate||b.wins-a.wins)[0],worst=[...eligible].sort((a,b)=>a.rate-b.rate||b.losses-a.losses)[0],ids=new Set(ats().filter(e=>e.attended).map(e=>e.game_id)),wg=gs().filter(g=>ids.has(g.id)&&done(g)),wins=wg.filter(g=>g.result==='W').length,unlocked=rs.reduce((n,r)=>n+badges(r).filter(b=>b[2]).length,0);root.innerHTML=`<div class="fan-section"><div class="fan-section-head"><div><h3>어흥 팬 기록</h3><p class="fan-muted">최소 ${MIN}경기부터 승률 랭킹에 반영됩니다.</p></div><button class="btn" data-fan-achievements>🏅 업적 도감</button></div><div class="fan-grid"><div class="fan-card"><h4>🧚 승리요정</h4>${rank(best)}</div><div class="fan-card"><h4>☠️ 패배요정</h4>${rank(worst)}</div><div class="fan-card"><h4>💙 직관 궁합</h4><div class="fan-compat-selects"><select id="fanPairA">${options()}</select><select id="fanPairB">${options(1)}</select><button class="btn" data-fan-compat>확인</button></div><div id="fanCompatResult" class="fan-muted">두 회원을 선택하세요.</div></div><div class="fan-card"><h4>🏟️ 좌석 도감</h4><div class="fan-stat">${seatData().length}/${SEATS.length}</div><button class="btn secondary" data-fan-seats>도감 열기</button></div><div class="fan-card fan-wrapped"><h4>✨ 어흥 ${new Date().getFullYear()} Wrapped</h4><div class="fan-stat">${wg.length}경기</div><div>${wins}승 · 직관 승률 ${wg.length?Math.round(wins/Math.max(1,wg.filter(g=>g.result!=='D').length)*100):0}%</div><button class="btn secondary" data-fan-wrapped>시즌 결산 보기</button></div><div class="fan-card"><h4>🏅 업적</h4><div class="fan-stat">${unlocked}</div><div class="fan-muted">전체 회원 누적 · 총 ${defs().length}종</div><button class="btn secondary" data-fan-achievements>전체 업적 보기</button></div></div></div>`;linkNames()}
  function rank(r){return r?`<button class="fan-member-button" data-fan-member="${r.member.id}">${safe(r.member.name)}</button><div class="fan-stat">${Math.round(r.rate*100)}%</div><div class="fan-muted">${r.wins}승 ${r.losses}패 · ${r.watched.length}경기</div>`:'<div class="fan-empty">기준 경기 수가 부족해요.</div>'}
  function modal(title,html){$('#fanModalTitle').textContent=title;$('#fanModalBody').innerHTML=html;$('#fanModal').classList.add('show')}
  function profile(id){const r=records().find(x=>x.member.id===id);if(!r)return;const bs=badges(r);modal(`${r.member.name}님의 직관 기록`,`<div class="fan-grid"><div class="fan-card"><h4>통산</h4><div class="fan-stat">${r.wins}승 ${r.losses}패</div><div>${r.draws}무 · 승률 ${Math.round(r.rate*100)}%</div></div><div class="fan-card"><h4>홈 / 원정</h4><b>홈 ${r.homeWins}승 ${r.homeLosses}패</b><br><b>원정 ${r.awayWins}승 ${r.awayLosses}패</b></div><div class="fan-card"><h4>직관 성향</h4><div>최다 상대 ${r.topOpponent?safe(r.topOpponent[0])+' '+r.topOpponent[1]+'경기':'-'}</div><div>평균 득점 ${r.avgRuns}</div></div></div><h4>업적 ${bs.filter(b=>b[2]).length}/${bs.length}</h4><div class="fan-achievement-grid">${bs.map(b=>achievement(b[0],b[1],b[3],b[4],b[2])).join('')}</div>`)}
  const achievement=(n,i,d,tone,on=true)=>`<div class="fan-achievement ${tone} ${on?'unlocked':'locked'}"><span>${i}</span><div><b>${n}</b><small>${d}</small></div></div>`;
  function catalog(){const rs=records();modal(`어흥 업적 도감 · ${defs().length}종`,`<p class="fan-muted">좋은 기록부터 웃픈 불명예 기록까지 조건을 모두 공개합니다.</p><div class="fan-achievement-grid">${defs().map(([n,i,d,test,tone])=>{const got=rs.filter(test);return`<div class="fan-achievement ${tone}"><span>${i}</span><div><b>${n}</b><small>${d} · ${got.length}명 달성</small>${got.length?`<div>${got.map(r=>`<button class="fan-member-button" data-fan-member="${r.member.id}">${safe(r.member.name)}</button>`).join(' · ')}</div>`:''}</div></div>`}).join('')}</div>`)}
  function compatibility(){const a=$('#fanPairA')?.value,b=$('#fanPairB')?.value,o=$('#fanCompatResult');if(!a||!b||!o)return;if(a===b)return o.textContent='서로 다른 회원을 선택해 주세요.';const p=pair(a,b);o.innerHTML=p.shared.length?`같이 본 <b>${p.shared.length}경기</b> · ${p.wins}승 ${p.losses}패 ${p.draws}무 · 궁합 <b>${p.score}점</b>`:'함께 완료한 직관 기록이 없습니다.'}
  function seats(){const set=new Set(seatData());modal('라팍 좌석 도감',`<div class="fan-seat-grid">${SEATS.map(s=>`<label class="fan-seat"><input type="checkbox" data-fan-seat value="${safe(s)}" ${set.has(s)?'checked':''}> ${safe(s)}</label>`).join('')}</div>`)}
  function wrapped(){const rs=records().sort((a,b)=>b.watched.length-a.watched.length),ids=new Set(ats().filter(e=>e.attended).map(e=>e.game_id)),wg=gs().filter(g=>ids.has(g.id)&&done(g));modal(`어흥 ${new Date().getFullYear()} 시즌 결산`,`<div class="fan-card fan-wrapped"><h3>올해 ${wg.length}경기를 직관했습니다.</h3><div class="fan-stat">최다 직관 ${rs[0]?safe(rs[0].member.name):'-'}</div></div>`)}
  function bind(){document.addEventListener('click',e=>{const t=e.target.closest('[data-fan-member],[data-fan-close],[data-fan-compat],[data-fan-seats],[data-fan-wrapped],[data-fan-achievements]');if(!t)return;if(t.dataset.fanMember)profile(t.dataset.fanMember);else if(t.hasAttribute('data-fan-close'))$('#fanModal').classList.remove('show');else if(t.hasAttribute('data-fan-compat'))compatibility();else if(t.hasAttribute('data-fan-seats'))seats();else if(t.hasAttribute('data-fan-wrapped'))wrapped();else catalog()});document.addEventListener('change',e=>{if(e.target.matches('[data-fan-seat]')){localStorage.setItem('eoheung_seat_catalog',JSON.stringify([...document.querySelectorAll('[data-fan-seat]:checked')].map(x=>x.value)));render()}})}
  function start(){ensure();bind();const old=window.renderAll;if(typeof old==='function')window.renderAll=function(){const x=old.apply(this,arguments);render();return x};render()}
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start):start();
})();
