(function(){
  function q(s){return document.querySelector(s)}
  function qa(s){return Array.from(document.querySelectorAll(s))}
  function say(m){var el=q('#toast');if(el){var d=document.createElement('div');d.textContent=m;el.appendChild(d);setTimeout(function(){d.remove()},3000)}else console.warn(m)}
  function css(){if(q('#accountPanelStyle'))return;var s=document.createElement('style');s.id='accountPanelStyle';s.textContent='.nav button[data-page="settings"]{display:none!important}.syncbox{position:relative!important;overflow:visible!important;padding:0!important;border:0!important;background:transparent!important;color:inherit!important}.account-shell{position:relative;display:grid;gap:8px}.account-bar{display:flex;gap:8px;align-items:center;justify-content:flex-start}.account-trigger{min-width:0;max-width:190px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;border:1px solid #c8d7ec;background:#fff;color:#53647a;border-radius:2px;padding:10px 12px;font-size:12px;font-weight:700;cursor:pointer;pointer-events:auto}.account-trigger:focus{outline:3px solid rgba(7,76,161,.22)}.account-logout{border:1px solid #fecdd3;background:#fff1f2;color:#be123c;border-radius:2px;padding:10px 12px;font-size:12px;font-weight:900;cursor:pointer}.account-pop{position:fixed;left:18px;top:120px;width:340px;max-width:calc(100vw - 24px);background:#fff;color:var(--text);border:1px solid var(--line);border-radius:16px;box-shadow:0 24px 70px rgba(15,23,42,.28);padding:16px;z-index:99999;display:none}.account-pop.show,.account-shell:hover .account-pop,.account-shell:focus-within .account-pop{display:block}.account-pop h3{margin:0 0 4px;font-size:18px}.account-pop .account-email{font-size:12px;color:var(--muted);margin-bottom:12px}.account-form{display:grid;grid-template-columns:1fr 1fr;gap:8px}.account-section{border-top:1px solid var(--line);padding-top:13px;margin-top:13px}.theme-choice{display:grid;grid-template-columns:1fr;gap:8px;margin-top:8px}.theme-choice button{border:1px solid var(--line);background:#f8fbff;color:var(--text);border-radius:12px;padding:10px 12px;text-align:left;font-weight:900;cursor:pointer}.theme-choice button.active{border-color:var(--blue);background:#eef4ff;color:var(--blue)}.account-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:12px}@media(max-width:1200px){.account-pop{position:absolute;left:0;top:52px}}@media(max-width:560px){.account-form{grid-template-columns:1fr}.account-trigger{max-width:210px}}';document.head.appendChild(s)}
  function me(){var st=window.state;if(!st||!st.user)return null;var uid=String(st.user.id||''),email=String(st.user.email||'').trim().toLowerCase();return (st.members||[]).find(function(m){return String(m.auth_user_id||'')===uid})||(st.members||[]).find(function(m){return String(m.email||'').trim().toLowerCase()===email})||null}
  function keepDashboard(){var sec=q('#settings');if(sec&&sec.classList.contains('active')){sec.classList.remove('active');q('#dashboard')&&q('#dashboard').classList.add('active');qa('.nav button').forEach(function(b){b.classList.toggle('active',b.dataset.page==='dashboard')});if(q('#pageTitle'))q('#pageTitle').textContent='대시보드';if(q('#pageSub'))q('#pageSub').textContent='삼성 라이온즈 직관 모임 현황을 확인합니다.'}}
  function currentTheme(){return (window.state&&state.theme)||localStorage.getItem('eoheung_theme')||'default'}
  function fill(){var st=window.state,m=me();var email=st&&st.user?st.user.email:'';var e=q('#accountEmailText');if(e)e.textContent=email||'계정';var p=q('#accountPanelEmail');if(p)p.textContent=email?('로그인 계정: '+email):'로그인 계정 확인 중';var n=q('#accountName'),ph=q('#accountPhone');if(m){if(n&&!n.matches(':focus'))n.value=m.name||'';if(ph&&!ph.matches(':focus'))ph.value=m.phone||''}qa('[data-account-theme]').forEach(function(b){b.classList.toggle('active',b.dataset.accountTheme===currentTheme())})}
  function build(){css();keepDashboard();var box=q('.syncbox');if(!box)return;if(!q('#accountShell')){box.innerHTML='<span id="dbStatus" style="display:none">연결됨</span><button id="reloadAllBtn" style="display:none" type="button"></button><div class="account-shell" id="accountShell"><div class="account-bar"><button class="account-trigger" id="accountTrigger" type="button" onclick="window.eoOpenAccountPanel(event)"><span id="accountEmailText">계정</span></button><button class="account-logout" id="accountLogoutBtn" type="button" onclick="window.eoAccountLogout(event)">로그아웃</button></div><div class="account-pop" id="accountPanel"><h3>내 계정 설정</h3><div class="account-email" id="accountPanelEmail">로그인 계정 확인 중</div><div class="account-form"><input id="accountName" class="input" placeholder="이름"><input id="accountPhone" class="input" placeholder="전화번호"></div><div class="account-actions"><button class="btn" id="accountSaveBtn" type="button" onclick="window.eoSaveAccountProfile(event)">개인정보 저장</button></div><div class="account-section"><h3>화면 테마</h3><div class="theme-choice"><button type="button" data-account-theme="default" onclick="window.eoSetAccountTheme(event,\'default\')">기본 대시보드</button><button type="button" data-account-theme="groupware" onclick="window.eoSetAccountTheme(event,\'groupware\')">그룹웨어 느낌</button><button type="button" data-account-theme="excel" onclick="window.eoSetAccountTheme(event,\'excel\')">엑셀 업무표 느낌</button></div></div></div></div>'}fill()}
  window.eoOpenAccountPanel=function(ev){if(ev){ev.preventDefault();ev.stopPropagation()}build();var p=q('#accountPanel');if(p){p.classList.toggle('show');fill();try{q('#accountTrigger').focus()}catch(e){}}};
  window.eoAccountLogout=async function(ev){if(ev){ev.preventDefault();ev.stopPropagation()}if(window.state&&state.client)await state.client.auth.signOut()};
  window.eoSaveAccountProfile=async function(ev){if(ev){ev.preventDefault();ev.stopPropagation()}var st=window.state,m=me();if(!st||!st.client||!m)return say('연동된 회원 정보를 찾지 못했습니다.');var name=(q('#accountName')&&q('#accountName').value.trim())||'',phone=(q('#accountPhone')&&q('#accountPhone').value.trim())||'';if(!name)return say('이름을 입력해 주세요.');var btn=q('#accountSaveBtn');if(btn)btn.disabled=true;try{var r=await st.client.from('members').update({name:name,phone:phone}).eq('id',m.id).select().single();if(r.error)throw r.error;var i=(st.members||[]).findIndex(function(x){return String(x.id)===String(m.id)});if(i>=0)st.members[i]=r.data;try{if(typeof renderMembers==='function')renderMembers();if(typeof renderDashboard==='function')renderDashboard();if(typeof renderRecords==='function')renderRecords();if(typeof renderDateDetail==='function')renderDateDetail()}catch(e){}say('개인정보를 저장했습니다.');fill()}catch(e){say('개인정보 저장 오류: '+(e.message||e))}finally{if(btn)btn.disabled=false}};
  window.eoSetAccountTheme=function(ev,v){if(ev){ev.preventDefault();ev.stopPropagation()}if(typeof window.applyTheme==='function')window.applyTheme(v);else{localStorage.setItem('eoheung_theme',v);document.body.classList.toggle('theme-groupware',v==='groupware');document.body.classList.toggle('theme-excel',v==='excel');if(window.state)state.theme=v}fill()};
  function delegated(){if(window.__eoAccountDirectBound)return;window.__eoAccountDirectBound=true;document.addEventListener('pointerdown',function(e){if(e.target.closest&&e.target.closest('#accountTrigger,.account-trigger,#accountEmailText'))window.eoOpenAccountPanel(e)},true);document.addEventListener('click',function(e){var p=q('#accountPanel');if(p&&p.classList.contains('show')&&!e.target.closest('#accountPanel')&&!e.target.closest('#accountTrigger'))p.classList.remove('show')},true)}
  function boot(){build();delegated();setInterval(function(){build();fill();keepDashboard()},1500)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
